---
title: "Practicum 2 Technical Report"
author: "Joseph Spatz"
date: "3/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(dplyr)
library(ggplot2)
library(car)
library(MASS)
library(mice)
library(tidyr)
```

```{r}
library(haven)
dat <- read_dta("dat_p2.dta")
View(dat)
```

```{r}
##Data Processing
summary(dat)

dat$marital <- factor(dat$marital,levels = c(0,1), labels = c("Not Married", "Married"))

summary(dat$marital)
class(dat$marital)

dat$education <- factor(dat$education,levels = c(1,2,3), labels = c("Less than College", "College and More", "Uknown"))
summary(dat$education)

dat$job <- factor(dat$job,levels = c(1,2,3,4,5,6,7), labels = c("White Collar", "Blue Collar", "Unemployed", "Entrepreneur/Self-Employed", "Student", "Retired", "Uknown"))


dat$y <- factor(dat$y,levels = c(0,1), labels = c("No", "Yes"))

summary(dat$y)

dat$default<- factor(dat$default,levels = c(0,1), labels = c("No", "Yes"))


dat$housing <- factor(dat$housing,levels = c(0,1), labels = c("No", "Yes"))


dat$loan <- factor(dat$loan,levels = c(0,1), labels = c("No", "Yes"))


dat$price <- as.numeric(dat$price)

dat$poutcome <- factor(dat$poutcome,levels = c(1,2,3,4), labels = c("Failure", "Other", "Success", "Unknown"))


dat$campaign <- as.numeric(dat$campaign)
dat$pdays <- as.numeric(dat$pdays)
dat$previous <- as.numeric(dat$previous)
dat$duration <- as.numeric(dat$duration)
dat$balance <- as.numeric(dat$balance)
dat$age <- as.numeric(dat$age)

dat$contact <- factor(dat$contact,levels = c(1,2,3), labels = c("Cellular","Telephone","Unknown"))


dat$month <- factor(dat$month,levels = c(1,2,3,4,5,6,7,8,9,10,11,12), labels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))

dat$month_season <- factor(dat$month_season, levels = c(1,2,3,4), labels = c("Spring", "Summer", "Fall", "Winter"))


```




```{r}
#Model Selection
mod_1 <- glm(y ~ poutcome+age+job+education+housing+price+campaign+default+balance+contact+pdays+month+day+previous, family = "binomial",na.omit(dat))


mod_0 <- glm(y ~ 1 , family=binomial, na.omit(dat))

mod.1 = step(mod_0,
             scope=list(lower=mod_0, upper=mod_1),
             direction = "both", trace = T)
library(faraway)
sumary(mod.1)
anova(mod.1)


```

#Distributions of Variables
```{r}

###Missing Data

dat_mini_1 <- dplyr::select(dat,y,price,contact,month,education,balance,job,housing,default,age,campaign,poutcome)

#Missing Data Patterns 
md.pattern(dat_mini_1,plot = T, rotate.names = TRUE)


#More Missing Data Patterns
library(VIM)
Practicum = aggr(dat_mini_1, numbers=TRUE, sortVars=TRUE,combined = F, labels=names(dat_mini_1), cex.axis=.6, gap=0, ylab=c("Proportion of missingness","Missingness Pattern"),bar = FALSE)


```

```{r}
library(mice)
md.pattern(dat_mini_1, rotate.names = TRUE)

dat_mini_1$na_count <- apply(dat_mini_1, 1, function(x) sum(is.na(x)))
dat_mini_1 %>% count(na_count)

dat_mini_1 <- 
  dat_mini_1 %>% 
  filter(na_count <= 1)

md.pattern(dat_mini_1, rotate.names = TRUE)


dat_mini_1[sapply(dat_mini_1, is.numeric)] <- lapply(dat_mini_1[sapply(dat_mini_1, is.numeric)], function(x) ifelse(is.na(x), mean(x, na.rm = TRUE), x))

dat_mini_1_impute <- na.omit(dat_mini_1)
save(dat_mini_1_impute, file = "dat_imp_final.RData")


```
###Exploratory Data Analysis

```{r}
###Exploratory Data Analysis
load(dat_imp_final.Rdata)

```